Feature mma 460
mulesoft/mule-migration-assistant pull request #474
Opened 2021-04-12 12:37 UTC by holiday-sunrise

2021-07-20 22:32 UTC, afelisatti requested changes

2021-07-20 22:32 UTC, afelisatti commented on mule-migration-tool-engine/src/main/java/com/mulesoft/tools/migration/engine/project/structure/util/Exclusions.java
> +  // GIT(File.separator + ".gitignore"),
Hi, @holiday-sunrise. Thanks for this contribution. Can you revert this part (commit 0768bfe)? We can then merge the catalog bit and track the `.gitignore` part in #460.

2021-07-22 13:20 UTC, holiday-sunrise commented
done

2021-07-22 13:21 UTC, afelisatti submitted a review, later dismissed

2021-07-22 13:31 UTC, afelisatti approved these changes

2021-07-22 13:32 UTC, merged