Feature mma 465
mulesoft/mule-migration-assistant pull request #477
Opened 2021-04-12 12:38 UTC by holiday-sunrise

2021-07-14 13:41 UTC, mlischetti commented on mule-migration-tool-api/src/main/java/com/mulesoft/tools/migration/project/model/pom/Parent.java
> +/*
This change is not need to fix the issue, please remove it

2021-07-14 13:42 UTC, mlischetti commented on mule-migration-tool-api/src/main/java/com/mulesoft/tools/migration/project/model/pom/PomModel.java
> +  /**
This changes are not need to fix the issue, please remove it

2021-07-14 13:44 UTC, mlischetti requested changes
Hi @holiday-sunrise thanks for contributing to mma project.
Can you please isolate the core changes involved in this issue to make it mergeable?

2021-07-14 14:38 UTC, holiday-sunrise commented
how should i  isolate he core changes

2021-07-14 14:44 UTC, holiday-sunrise commented
Files have been removed

2021-07-14 14:51 UTC, mlischetti commented
@holiday-sunrise, there is a misunderstood about PomModel.java file.
What I was trying to said is that changes in PomModel.java are not needed not that you should remove the file itself.
Also an unit test would be great to add on current PR

2021-07-14 17:01 UTC, mlischetti commented
PomModel.java file still contains unnecessary modification please revert this changes

2021-07-15 07:02 UTC, holiday-sunrise commented
Pom model should now reverted. sorry my mistake

2021-07-15 12:57 UTC, mlischetti approved these changes
LGTM

2021-07-15 12:58 UTC, merged