Add generic unsupported elements handling steps and implement the fist use for the Salesforce connector
mulesoft/mule-migration-assistant pull request #613
Opened 2022-03-31 00:48 UTC by jesica-fera

* Also fix unsupported namespace handling to comment unsupported elements instead of leaving them with just an error

On the salesforce connector this is fixing cases using config-oauth-user-pass for now because it was reported but more elements can be added if needed

2022-04-01 17:56 UTC, jesica-fera commented
This is a fix for https://github.com/mulesoft/mule-migration-assistant/issues/564

2022-04-04 13:24 UTC, svacas requested changes

2022-04-04 13:24 UTC, svacas commented on mule-migration-tool-e2e-tests/src/test/resources/e2e/gaps/salesforce_config_oauth_user_pass/output/report/report.json
> +      "component": "mule",
should report `sfdc:config-oauth-user-pass` as the error component with its line and col numbers

2022-04-04 13:24 UTC, svacas commented on mule-migration-tool-e2e-tests/src/test/resources/e2e/gaps/salesforce_config_oauth_user_pass/output/report/report.json
> +      "component": "mule",
should report `sfdc:config-oauth-user-pass` as the error component with its line and col numbers

2022-04-04 13:24 UTC, svacas commented on mule-migration-tool-e2e-tests/src/test/resources/e2e/gaps/unknown_namespace/output/report/report.json
> +      "component": "flow",
should report `unknown:source` as the error component with its line and col numbers

2022-04-04 13:24 UTC, svacas commented on mule-migration-tool-e2e-tests/src/test/resources/e2e/gaps/unknown_namespace/output/report/report.json
> +      "component": "flow",
should report `unknown:operation` as the error component with its line and col numbers

2022-04-05 23:43 UTC, jesica-fera commented
I am closing this PR in favor of this one https://github.com/mulesoft/mule-migration-assistant/pull/614 because fixing this properly requires a bigger refactor. When the components are commented out, reporting the right element and location becomes complex because there are several cases where elements are mutated so location and parent element are not easy to calculate. For now I am creating the second PR to fix the actual original issue.

2022-04-05 23:43 UTC, closed without merging