Add edge from referenced flows back to original
mulesoft/mule-migration-assistant pull request #632
Opened 2022-05-11 18:58 UTC by jesica-fera

2022-05-12 15:47 UTC, svacas requested changes
I've rendered the graph for `nocompatibility-01` test and found these three errors, two arrows that shouldn't be there and 1 arrow missing:
<img width="1402" alt="nocomp-01" src="https://user-images.githubusercontent.com/557476/168115288-f54fe05f-18ef-4835-81a1-e1edb6dbe050.png">
Also I see `MessageSource` coming back.

2022-05-12 23:34 UTC, jesica-fera commented
For some reason I can't reply to the comment here. MessageSource was there because this was not rebased from the last change in the main branch I think. I did a rebase now.

Also I fixed the issue you mentioned. The graph of the example you put is now: 

![nocompatibility-01](https://user-images.githubusercontent.com/987652/168183932-7c73c874-bb90-48fb-b0c9-daf2ba9169d3.png)

2022-05-16 19:24 UTC, jesica-fera commented
Fixed the clashing name bugs, new graph for `nocompatibility-05` is

![nocompatibility-05](https://user-images.githubusercontent.com/987652/168667025-4429dea8-b2a6-4e9a-88c8-4104991ff8d2.jpg)

2022-05-16 19:58 UTC, svacas approved these changes

2022-05-16 20:30 UTC, merged